---
title: "CellChatTutorial"
output: html_document
---

#Install Packages
```{r}
source("~/AXL-PD1/src/globals/constants.R")
CODE_DIR_PATH <- "~/Thesis/CellChat"
install.packages("remotes")
install.packages("fastmap")
remotes::install_github("sqjin/CellChat")
source("~/AXL-PD1/src/requirements.R")
source(file.path(CODE_DIR_PATH, "utils/Utils.FH.R"))
source(file.path(CODE_DIR_PATH, "utils/RNA.seq.Utils.R"))
source(file.path(CODE_DIR_PATH, "utils/Utils.R"))

library(CellChat)
library(patchwork)
library(Seurat)
```
#Load Seurat Object
```{r}
SC.3CA.Tirosh.Head_And_Neck.Input.Path <- file.path(DATA_DIR_PATH, "SC.3CA.Tirosh/Head_and_Neck")

my.save.RData("Kurten.2021.Seurat", myfolder=SC.3CA.Tirosh.Head_And_Neck.Input.Path, is.load.obj = T)
```


```{r}
data.input <- GetAssayData(Kurten.2021.Seurat, assay="alra", slot="data")
meta <- data.frame(group = Kurten.2021.Seurat@meta.data$cell_type)
rownames(meta) <- colnames(Kurten.2021.Seurat)

cellchat <- createCellChat(object=data.input, meta=meta, group.by = "group")

CellChatDB <- CellChatDB.human
cellchat@DB <- CellChatDB

cellchat <- subsetData(cellchat)
cellchat <- identifyOverExpressedGenes(cellchat)
cellchat <- identifyOverExpressedInteractions(cellchat)
cellchat <- computeCommunProb(cellchat)
cellchat <- filterCommunication(cellchat, min.cells = 10)
cellchat <- computeCommunProbPathway(cellchat)
cellchat <- aggregateNet(cellchat)

netVisual_circle(cellchat@net$count, vertex.weight = T)
netAnalysis_signalingRole_heatmap(cellchat)
```

